#-----------------------------------------------------------------------
APP       := MiniGame
TARGET    := libgame-wsk.so
CONFIG    :=
STRIP_FLAG:= N

LFLAGS    := -fPIC
MFLAGS :=32

#-----------------------------------------------------------------------

include /home/tafjce/MiniGame/Comm/Comm.mk
include /usr/local/taf/makefile.taf

#-----------------------------------------------------------------------

