// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Ans_PushDialogBox.proto

#ifndef PROTOBUF_Ans_5fPushDialogBox_2eproto__INCLUDED
#define PROTOBUF_Ans_5fPushDialogBox_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
// @@protoc_insertion_point(includes)

namespace tutorial {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_Ans_5fPushDialogBox_2eproto();
void protobuf_AssignDesc_Ans_5fPushDialogBox_2eproto();
void protobuf_ShutdownFile_Ans_5fPushDialogBox_2eproto();

class Ans_PushDialogBoxMsg;

// ===================================================================

class Ans_PushDialogBoxMsg : public ::google::protobuf::MessageLite {
 public:
  Ans_PushDialogBoxMsg();
  virtual ~Ans_PushDialogBoxMsg();
  
  Ans_PushDialogBoxMsg(const Ans_PushDialogBoxMsg& from);
  
  inline Ans_PushDialogBoxMsg& operator=(const Ans_PushDialogBoxMsg& from) {
    CopyFrom(from);
    return *this;
  }
  
  static const Ans_PushDialogBoxMsg& default_instance();
  
  void Swap(Ans_PushDialogBoxMsg* other);
  
  // implements Message ----------------------------------------------
  
  Ans_PushDialogBoxMsg* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const Ans_PushDialogBoxMsg& from);
  void MergeFrom(const Ans_PushDialogBoxMsg& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::std::string GetTypeName() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required int32 params = 1;
  inline bool has_params() const;
  inline void clear_params();
  static const int kParamsFieldNumber = 1;
  inline ::google::protobuf::int32 params() const;
  inline void set_params(::google::protobuf::int32 value);
  
  // required string content = 2;
  inline bool has_content() const;
  inline void clear_content();
  static const int kContentFieldNumber = 2;
  inline const ::std::string& content() const;
  inline void set_content(const ::std::string& value);
  inline void set_content(const char* value);
  inline void set_content(const char* value, size_t size);
  inline ::std::string* mutable_content();
  inline ::std::string* release_content();
  
  // repeated string extra = 3;
  inline int extra_size() const;
  inline void clear_extra();
  static const int kExtraFieldNumber = 3;
  inline const ::std::string& extra(int index) const;
  inline ::std::string* mutable_extra(int index);
  inline void set_extra(int index, const ::std::string& value);
  inline void set_extra(int index, const char* value);
  inline void set_extra(int index, const char* value, size_t size);
  inline ::std::string* add_extra();
  inline void add_extra(const ::std::string& value);
  inline void add_extra(const char* value);
  inline void add_extra(const char* value, size_t size);
  inline const ::google::protobuf::RepeatedPtrField< ::std::string>& extra() const;
  inline ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_extra();
  
  // @@protoc_insertion_point(class_scope:tutorial.Ans_PushDialogBoxMsg)
 private:
  inline void set_has_params();
  inline void clear_has_params();
  inline void set_has_content();
  inline void clear_has_content();
  
  ::std::string* content_;
  ::google::protobuf::RepeatedPtrField< ::std::string> extra_;
  ::google::protobuf::int32 params_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];
  
  friend void  protobuf_AddDesc_Ans_5fPushDialogBox_2eproto();
  friend void protobuf_AssignDesc_Ans_5fPushDialogBox_2eproto();
  friend void protobuf_ShutdownFile_Ans_5fPushDialogBox_2eproto();
  
  void InitAsDefaultInstance();
  static Ans_PushDialogBoxMsg* default_instance_;
};
// ===================================================================


// ===================================================================

// Ans_PushDialogBoxMsg

// required int32 params = 1;
inline bool Ans_PushDialogBoxMsg::has_params() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Ans_PushDialogBoxMsg::set_has_params() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Ans_PushDialogBoxMsg::clear_has_params() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Ans_PushDialogBoxMsg::clear_params() {
  params_ = 0;
  clear_has_params();
}
inline ::google::protobuf::int32 Ans_PushDialogBoxMsg::params() const {
  return params_;
}
inline void Ans_PushDialogBoxMsg::set_params(::google::protobuf::int32 value) {
  set_has_params();
  params_ = value;
}

// required string content = 2;
inline bool Ans_PushDialogBoxMsg::has_content() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Ans_PushDialogBoxMsg::set_has_content() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Ans_PushDialogBoxMsg::clear_has_content() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Ans_PushDialogBoxMsg::clear_content() {
  if (content_ != &::google::protobuf::internal::kEmptyString) {
    content_->clear();
  }
  clear_has_content();
}
inline const ::std::string& Ans_PushDialogBoxMsg::content() const {
  return *content_;
}
inline void Ans_PushDialogBoxMsg::set_content(const ::std::string& value) {
  set_has_content();
  if (content_ == &::google::protobuf::internal::kEmptyString) {
    content_ = new ::std::string;
  }
  content_->assign(value);
}
inline void Ans_PushDialogBoxMsg::set_content(const char* value) {
  set_has_content();
  if (content_ == &::google::protobuf::internal::kEmptyString) {
    content_ = new ::std::string;
  }
  content_->assign(value);
}
inline void Ans_PushDialogBoxMsg::set_content(const char* value, size_t size) {
  set_has_content();
  if (content_ == &::google::protobuf::internal::kEmptyString) {
    content_ = new ::std::string;
  }
  content_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Ans_PushDialogBoxMsg::mutable_content() {
  set_has_content();
  if (content_ == &::google::protobuf::internal::kEmptyString) {
    content_ = new ::std::string;
  }
  return content_;
}
inline ::std::string* Ans_PushDialogBoxMsg::release_content() {
  clear_has_content();
  if (content_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = content_;
    content_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// repeated string extra = 3;
inline int Ans_PushDialogBoxMsg::extra_size() const {
  return extra_.size();
}
inline void Ans_PushDialogBoxMsg::clear_extra() {
  extra_.Clear();
}
inline const ::std::string& Ans_PushDialogBoxMsg::extra(int index) const {
  return extra_.Get(index);
}
inline ::std::string* Ans_PushDialogBoxMsg::mutable_extra(int index) {
  return extra_.Mutable(index);
}
inline void Ans_PushDialogBoxMsg::set_extra(int index, const ::std::string& value) {
  extra_.Mutable(index)->assign(value);
}
inline void Ans_PushDialogBoxMsg::set_extra(int index, const char* value) {
  extra_.Mutable(index)->assign(value);
}
inline void Ans_PushDialogBoxMsg::set_extra(int index, const char* value, size_t size) {
  extra_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Ans_PushDialogBoxMsg::add_extra() {
  return extra_.Add();
}
inline void Ans_PushDialogBoxMsg::add_extra(const ::std::string& value) {
  extra_.Add()->assign(value);
}
inline void Ans_PushDialogBoxMsg::add_extra(const char* value) {
  extra_.Add()->assign(value);
}
inline void Ans_PushDialogBoxMsg::add_extra(const char* value, size_t size) {
  extra_.Add()->assign(reinterpret_cast<const char*>(value), size);
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
Ans_PushDialogBoxMsg::extra() const {
  return extra_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
Ans_PushDialogBoxMsg::mutable_extra() {
  return &extra_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace tutorial

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_Ans_5fPushDialogBox_2eproto__INCLUDED
